version: "3.8"

services:
  cadence:
    image: uber/cadence-server:master-auto-setup
    ports:
      - "7933:7933" # gRPC
      - "8088:8088" # Web UI
    volumes:
      - ./cadence_data:/var/lib/cadence
