# Spring Boot Configuration
server.port=8081
spring.application.name=temporal-saga-example

# Temporal Connection Configuration
spring.temporal.connection.target=127.0.0.1:7233
spring.temporal.namespace=default
spring.temporal.workers.default.task-queue=SIGNUP_TASK_LIST
spring.temporal.workers.user-activities.task-queue=SIGNUP_TASK_LIST
spring.temporal.workflow-packages=com.example.cadence.workflow
spring.temporal.activity-packages=com.example.cadence.activity
